### ISSUE TITLE
Build in Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by prool** [kilobyte/kbtin#6]
Hello!

I'm trying to build kbtin in Ubuntu 20.04.1 LTS x86_64

and have error message:

./autogen.sh
./configure

...

checking for cfmakeraw... yes
checking for strlcpy... no
./configure: line 4667: syntax error near unexpected token `ZLIB,zlib,,'
./configure: line 4667: `    PKG_CHECK_MODULES(ZLIB,zlib,,'

**Comment by kilobyte** [comment]
To recreate the autoconfage, you need `pkg-config` installed.

The installation documentation talks only about old-style dist tarballs that hardly anyone uses these days.  I've extended it to provide more information, hopefully that should be good enough.
